# Language Development at Scale {#scale}

This chapter synthesizes knowledge gained from the broader wordbank package, in the sense of attempting to make generalizations about early language development that hold true across the different datasets in our sample. 


1. The first words are very consistent across languages and largely social in nature
2. Early social/communicative gesture is correlated with language.
3. Across children, variability is a constant in early language.
4. While there is a noun bias in early language, verbs/adjectives vary by language.
5. The growth of grammar is linked to vocabulary growth.



Wordbank embodies our belief that scale is in itself transformative. The existence of a noun bias is a fascinating observation, but this observation gives limited leverage to differentiate theories. The magnitude of a noun bias provides more leverage for quantiative theorizing. And the distribution of magnitudes across many of the world's languages gives greater leverage still. Our hope is that, by generalizing and applying many influential analyses by many contributors, our work here can affect theory more broadly.

More ABOUT POWER TO MEASURE MEAN AND VARIANCE

REPRODUCIBILITY

Developmental psychology often appears to be divided between two groups that do not communicate with one another. On the one hand, there are researchers interested in the ontogenetic and phylogenetic origins of knowledge -- the epistemological project of understanding how we reason about objects, communicate using language, or learn from other people [@carey2009, @spelke2007, @tomasellooriginoflanguage]. On the other hand, there are researchers interested in growth, change, and variation across individuals in psychometric constructs like executive function, working memory, and personality [@zelazo?, other cites]. The first type of research has led to a productive union of philosophical and psychological ideas, addressing many of the most exciting questions in the history of philosophy using empirical methods [@gopnik, @carey]. The second type has had success in its connections to educational policy [@nelson2007,@diamond2011, others?]. In many areas of research, these two traditions have little interchange with one another. They read different journals, record different measures, use different research designs and statisical models, and often appear to be pursuing entirely different goals. 

Yet language learning is an area where these traditions come together. The knowledge being acquired -- the stock of words in the child's lexicon -- is both the epistemic construct whose origins we are studying *and* the psychometric construct whose reliability across individuals we wish to assess. By studying the variability and consistency in the early lexcion, we can both study the origins of knowledge and the processes and factors by which human beings differ from one another across different cultural contexts, family environments, and genetic endowments.

