# Language Development at Scale {#conclusion-scale}

This chapter synthesizes knowledge gained from the broader enterprise, in the sense of attempting to make generalizations about early language development that hold true across the different datasets in our sample. We begin by briefly reviewing the content of our findings across the preceding substantive chapters. Next, we discuss three synthetic generalizations from these findings. We then turn to the question of the particular process universals that might be compatible with this empirical picture.

## Summary

We began with the question of what parent report can tell us about children's early language. We are now in a better position to answer this question, summarizing findings across the content chapters of the manuscript. 

In Chapter \@ref(psychometrics), we reviewed evidence for the reliability and validity of parent report instruments for assessing children's early language, with generally positive conclusions. Further, we contributed two sets of novel analyses. First, examining large-scale longitudinal datasets, we estimated the fall-off in test-retest correlations over developmental time, which suggested a relatively high level of reliability overall. Second, we used item response theory (IRT) models to examine the measurement properties of individual words on the CDI. Overall most items had strong psychometric performance, and even comprehension reports appeared to have consistent informational value about a child's overall abilities (although individual items appeared less diagnostic on average than production reports). The broad picture from this chapter was positive, motivating further use of CDI data. 

Chapter \@ref(vocabulary) then examined trends in the growth and distribution of individual vocabulary estimates. Across languages, and for production and comprehension, early vocabulary development starts slow and grows rapidly in the second year after birth. There are both absolute and relative differences between languages in the estimated rate of vocabulary growth, however. While some of these may reflect true differences (for example, Danish being famously difficult to acquire), others likely stem from differences in instrument, sample, and administration conditions. On the other hand, we observed a striking consistency across languages in the degree to which children varied. This finding suggests the operation of individual- and dyad-level processes that vary systematically in a way that is somewhat independent of the precise content being acquired and the cultural background of acquisition. On average, language emerges quickly -- but despite the average pattern, toddlers around the world are "all over the place" in their learning rate. Indeed, one of the most compelling universals in language development is the variation that is observed across children.

Chapter \@ref(demographics) considered demographic predictors of vocabulary size. We found a general female advantage in early vocabulary that was more pronounced for production than comprehension. This advantage did not appear to stem from reporting bias, and was relatively consistent in size across languages. We also observed a first-born advantage and an advantage for children with more-educated mothers (likely a proxy for general socio-economic status). Chapter \@ref(items-demographics) followed up these analyses by identifying whether specific words were the locus of some of these differences. The conclusion of these analyses were that there were *both* general demographic differences in vocabulary *and* word-specific differences. For example, girls, on average, both have a higher probability of knowing any word, and they also have a much higher probability of knowing words like "dress" and "doll."

Turning to gestural communication, Chapter \@ref(gesture) showed that children's uses of early gestures are both quite consistent with one another and quite consistent across languages. In other words, gestures appear to group together as part of a set of communicative abilities (rather than existing as isolated items). A small set of similar gestures are often the earliest emerging across languages, likely arising from relatively universal dyadic needs (e.g., a signal for "pick me up" or "give me"). Finally, variation in early gestures is quite well correlated with variation in early vocabulary within individuals.

Like early gestures, early words are often surprisingly similar across languages. In Chapter \@ref(items-consistency), we quantified this similarity and showed that it was related to typological relatedness. On the other hand, a number of words occur in children's earliest vocabulary, even across quite dissimilar languages. Like early gestures, these early vocabulary items likely reflect relatively universal communicative needs in infant-caregiver dyads. (We return to this theme below in Section \@ref{generalizations}). 

In Chapter \@ref(items-prediction), we extended this approach to the composition of vocabulary by creating predictive models of the ease or difficulty of individual words. These models, uniquely in our analyses, take into account the average environmental input for a learner of a particular language (estimated from corpus resources). Although a number of factors including input, conceptual factors, and phonological complexity interact to predict when words are first understood or produced, the profile of predictors across languages was quite similar. We interpret this finding to point to a relatively consistent set of processes that are operating in different linguistic contexts. 

Following the thread of cross-linguistic differences, Chapter \@ref(categories-syntactic) examined the question of the syntactic composition of vocabulary across early development. Consistent with previous reports, we found that most languages exhibited a bias towards nouns, although the strength of that bias varied across languages.  Further, essentially all languages showed a developmental bias against function words. On the other hand, the bias for predicates (verbs and adjectives) was more variable across languages, with most languages showing a negative bias, but a few (Mandarin and Cantonese, in particular) showing a neutral or positive bias. This pattern of variability points to some language-specific factors (perhaps syntactic structure, perhaps other linguistic or interactional factors) that influence learning within particular syntactic categories. 

We next applied this same approach to semantic categories (Chapter \@ref(categories-semantic)). Computing the relative bias for or against particular semantic categories, we found some cross-linguistic consistency in early biases: biases for body parts, games, and onomatopoeia were quite consistent; biases against words for places and time were as well. These biases suggest that there are likely some attentional and conceptual biases that facilitate or inhibit word learning in similar ways across languages. 

Turning next to syntactic development, Chapter \@ref(grammar) showed that children's morphological and grammatical ability appears tightly coupled with their vocabulary size. This generalization holds very consistently across languages, validating Bates' speculation that there is a general law of language development that is shared across vocabulary and grammar learning. This chapter also extended earlier analyses of these relations by identifying a moderating effect of age on this relationship such that older children appear to gain more "units grammar" per "unit vocabulary" -- that is, grammar emerges slightly faster for these older, compared to younger, children. 

The last empirical chapter, Chapter \@ref(style), examined individual variability in language. This chapter presented evidence for the "referential" vs. "expressive" distinction -- that, even controlling for overall developmental level, some children appear to have larger, "noun-ier" vocabularies while others have smaller vocabularies but are more likely to combine words. Similarly, some children certainly produce relatively more of their total vocabulary than others (though these measurements are difficult to validate independent of reporting variability). On the other hand, we did not observe strong evidence for the idea that some children's vocabulary growth is particularly "spurt-y" -- rather, once statistical artifacts are accounted for, vocabulary growth appears to accelerate relatively smoothly in all children, varying quantitatively along a rate continuum. 

Finally, in the previous chapter, Chapter \@ref(conclusion-consistency), we attempted to consolidate the cross-linguistic variability in all of the findings above and place these on a single axis. This comparison revealed a number of patterns that we take up in our generalizations below. 

## Generalizations {#generalizations}

What is the picture of language development that emerges from these individual findings? We now return to the theoretical project of Chapter \@ref(intro-theory), which was to use patterns of consistency and variability to provide constraints on theories of early language learning. We begin by considering three major generalizations from our data, and then turn back to the question of possible learning processes that could support these generalizations.

### The language system is tightly woven

It could easily be the case that children are "pointy" with respect to language -- that is, highly proficient in some sub-aspect of languages and poor at others. A naive examiner of a group of children in a toddler classroom might conclude that the variation that they observed was supportive of such a view. In such a classroom, some children will only be able to gesture and say a few words; while some others will appear to show a large noun bias; and still others will be fluently combining words. Furthermore, these children will be distributed across a range of ages, with this progress only somewhat predicted by relative age (especially in a tightly-grouped sample from say 18--30 months). 

This viewpoint is largely incorrect, however. Instead, the language system is tightly woven together, such that, on the whole, children who are good at gestures have a larger vocabulary, and children who have a larger vocabulary also inflect and combine words more proficiently. These correlations within individuals are large and they are universal across those languages in which we can evaluate them. Further, while these correlations could, in principle, arise in CDI data from parent reporting bias across sections of a single form, they are also largely borne out in a variety of observational and behavioral datasets [e.g., @brinchmann2018; @rowe2009]. 

How can the consistence and coherence of these distinct aspects of early language be reconciled with the type of variation our preschool observer might see? Consider the following model of early language. The first posit of this model is that the trajectory of children's learning follows a single, coherent path through the stages of early language. Initially, gestures and early nouns and social routines are learned. Nouns follow, leading into verbs. Verbs in turn promote word combination and morphology. The second posit is that aspects of this trajectory may be non-linear: the noun bias increases and then decreases [@bates1994]; the relation between lexicon and grammar may be flatter at one period than another [@dixon2007]. Finally, imagine a third posit: this non-linear trajectory is followed at different rates, with a child's current state partially a function of age and partially a function of their own idiosyncratic learning rate. 

Under such a "unitary non-linear trajectory" model, we would still see "pointy" children in the preschool classroom. These children would be cross-sections cut from the same trajectory, but at different points along it. The younger child who knows a surprising number of names might be further along relative to age and hence firmly in the "noun bias" part of the general path. In contrast, the older child who primarily gestures might be a child with a slightly slower growth rate. Observed variation need not indicate that the subparts of language do not "hang together" (to return to the Batesian phrasing). We return below to the analyses of true variation in learning style that are reported in Chapter \@ref(style).

Alongside its support from the cross-linguistic consistency in cross-domain correlations, this unitary view of early language is supported by several other bodies of work. The first is a set of longitudinal analyses by Bornstein and colleagues. In a two-cohort longitudinal study, @bornstein1998 and @bornstein2004b collected data from a sample of American English learning children at two and four years and measured language using a variety of instruments including parent report, transcripts, and behavioral tasks. In a re-analysis of these data, @bornstein2012 found that the core construct of early language that emerged from the sub-measures was both highly correlated with each of the sub measures and also highly stable over time (as we noted earlier in Chapter \@ref(psychometrics)). 

In addition, research on international adoption, a unique case study of changes in learning rate relative to input, provides support for this unitary trajectory view as well. International adoptees often have to let go of their native language completely, sometimes at a fairly old age, and begin learning a host language. A body of work by Snedeker, Geren, and Shafto [-@snedeker2007;-@snedeker2012] suggests that these children go through the same general course of acquisition, including an early noun bias and early grammatical omissions, but they did so much more quickly on average then native learners. Although these children were more conceptually sophisticated and could learn faster, the informational challenges of breaking into the language were still similar on the whole. 

In sum, the language system is much more tightly woven than casual observation might lead an observer to expect. Our work here confirms and extends previous investigations by @bates1994 and @bornstein2012.  Although our data provided multiple opportunities for aspects of language development (communication, vocabulary, morphology, grammar) to pull apart across individuals into modular subsystems, they instead hung together very tightly. Further, the strength of these connections did not vary across every language examined: the nature of the trajectory was surprisingly consistent, even across languages with substantial differences in morphosyntactic structure. 

<!-- look at grammar lex t1 - t2 in norwegian/english -->

<!-- Could do IRT on the grammar items? Look at distribution univariate, and also  -->


### Young children talk about similar things 

A second broad generalization from our work here is the content similarities in children's early vocabulary across languages. Put simply, regardless of the language they are learning, children in the early stages of language learning appear to talk about similar things, especially people, social routines, small objects, and body parts. This work builds on analyses by @tardif2008, who compared the distribution of children's first ten words across three languages. Many of the content generalizations that held for those three languages in fact hold here as well in a much more broad array of languages. 

As with the example above, it is useful to consider the counterfactual situations, which are very reasonable *a priori*. Without knowing anything about language acquisition in other languages, we might suppose that children in different cultures begin speaking about quite different things. We could easily imagine a culture in which children primarily began by describing the properties of objects: "soft!" "small!" or another in which children described places or another in which children talk about places they go or things around the house. We might think that American children are obsessed with animals, whereas, children in other cultures might abhor them. It turns out that all of these counterfactuals are largely not observed. 

We observed three broad categories of findings that support this generalization.  First, relating most directly to @tardif1999's work, in Chapter \@ref(items-consistency), we observed a strong correlation in the rank order of acquisition for the earliest words. Those words that were typically learned very early in one language tended to be very early learned in others. These correlations were attenuated for later-learned words. Second, we saw that some word categories -- both syntactic and semantic categories -- were typically over-represented across languages, while others were under-represented. Nouns generally were over-represented (with some cross-linguistic variability in the amount of over-representation). But beyond that, words for body parts, games and social routines, and sounds were all over-represented. In contrast, predicates and function words, as well as words for time and places were under-represented. And third, when we looked for systematic predictors of the ease of learning words across language, the predictor "babiness" -- which captures association with infants -- was among the strongest predictors, especially for early-learned words. 

Where do these similarities come from? Before answering this question, we can say that they likely *do not* emerge from simple linguistic or environmental frequency. Not only is frequency statistically controlled in some of our analyses (e.g., those in Chapter \@ref(items-prediction)), but also there are clear dissociations between linguistic frequency and children's comprehension and production. Although mothers and fathers are likely common in children's experience, "mom" and "dad" (or the local equivalent) are actually relatively infrequent in language directed to children -- yet they are uttered very early, sometimes even first. Many function words are highly frequent in speech to children, yet are produced much later than expected. Finally, many omnipresent environmental stimuli from diapers to couches and carpets are referred to only much later than the people, animals, and small objects on and in them. 

Instead, these similarities likely emerge from a combination of children's particular attention and interests; the communicative priorities of child-caregiver dyads; and the informational structure of language, which renders certain aspects of language easier to learn than others. We consider each of these in turn. 

First, although we do not have an independent operationalization of children's specific interests, anyone who has spent time with toddlers can say that these interest are present and extremely powerful. The red puppet Elmo, who has a squeaky (some might say annoying) voice, is almost designed to drive children's attention and interest, despite some parents' best efforts to minimize his frequency in the environment. More generally, toddlers tend to make a bee-line towards animals and toys that they perceive as interesting. These preferences may stem from general conceptual preferences for animates, or broader perceptual preferences, or likely some mixture of the two, but their impact on children's attention -- and from there their vocabulary across languages -- is undeniable. 

Second, it is also true that children's own attention is far from the only driver of the language they hear. Children's language exposure takes place in an environment that is largely constructed by their caregivers, rather than them. Thus, much of the language they hear is "functional talk" that takes place in the context of routines like dressing, diapering, mealtime, and bathtime. These dyadic priorities mean that children's vocabulary often contains a wide variety of functional terms. In fact, @roy2015 even argued that the contextual distinctiveness of words that appear in these routines may lead to earlier acquisition. Similar dyadic priorities across cultures would thus lead to cross-linguistic consistency in early vocabulary. 

Finally, some words may be learned earlier than others simply because of the informational structure of language. As argued by @snedeker2007, verbs may be later-learned simply because you need to know some nouns to figure them out. To the extent that these regularities extend across languages, they would impose a variety of ordering constraints on acquisition that could be reflected in our analyses. 

Of course, it is always possible that we might observe more variation to the extent that relatively more variant languages exist. All of the typological caveats that we first stated in Chapter \@ref(intro-theory) hold still: most of our languages are WEIRD [@henrich2010], and the majority are Indo-European. Especially with respect to assessing semantic variation across languages, it will be critical for future work to incorporate a wider range of languages and language families. 


### Children take different routes into language

Despite these aggregate similarities across children and across cultures, children individually take different routes into language. The speed with which they acquire language is highly variable in the first years of life and this variability itself is a constant across cultures. Further, children vary stably in the nature of their acquisition path, some naming more objects and others combining words relatively more.

First, even controlling for the non-linear trajectory of acquisition mentioned above, we found stable differences in "referential style" among children. Thus, although the language system is tightly woven and moves through a relatively consistent learning trajectory across individuals, there is nevertheless an interesting, second-order component. Some children, especially the faster-learning ones, appear to learn more nouns. Others, often the slower-learning ones, tend to combine words more frequently. This pattern may relate to the age-moderation found in Chapter \@ref(grammar): it is precisely the older children who gain more "grammar per unit lexicon." Perhaps those children who are learning slightly more slowly then are able to bring more mature working memory to the task of grammatical induction. Or perhaps these children have heard more language and hence the natural statistics of language are easier to extract. Or perhaps these early word combinations are actually "unanalyzed wholes" that are syntactically less complex than they might appear.  Regardless, these differences appear as a stable aspect of the relatively consistent developmental course we observed. 

<!-- check to see if unanalyzed wholes is discussed in chapter 14 -->

Beginning with the first monograph reporting the CDI norming study, @fenson1994 noted that variability is perhaps the primary and most striking fact about children's vocabulary learning. In practical terms, the huge variance across children accounts for the fact that while some typically-developing two year olds will talk your ear off, others will barely utter a handful of words (even if they understand more). From a biological perspective, this variability is quite unprecedented. As a comparison, variation in heights for toddlers is tiny compared with variation in vocabulary: the mean height for a 24-month-old is around 33 inches, with a standard deviation of a little more than an inch, leading to a coefficient of variation around .03. This measurement is almost two orders of magnitude smaller than the coefficient of variation on vocabulary.
 
Examining the variability in English-learning children's vocabulary documented by @fenson1994, it was easy to think that the spread of children's outcomes was due to the demographic and parenting variability found in the United States, which -- even in the restricted set sampled in that initial study -- was large. But a look at the variability estimates found in our broader sample dispels this hypothesis -- the variability is surprisingly constant (and large) across every language we examined. If culture homogeneity was an important influence on the homogeneity of early language, we would expect a smaller variability measurement for the Norwegian, Korean, or Chinese populations, where cultural, educational, and socio-economic heterogeneity would be expected to be higher. Instead, these populations show a similar level of variation. 

Where does this variability come from? We can only speculate. Some must come from variation in input across households, which has been amply documented to relate to children's early vocabulary [e.g., @hart1995;@hoff2003;@weisleder2013]. Further, some component of this input-correlated variation is likely to be genetic [e.g., @hayiou-thomas2012], such that some children inherit a tendency towards slower vocabulary growth from parents who themselves talk relatively less and use relatively less diverse vocabulary. 

Does this variation persist beyond the range of our study? One of the most intriguing aspects of our analysis is the suggestion that, accounting for ceiling effects, variation in ability does not compress in the range we measured. An important direction for future work would be to ask about the range of variation observed within and across cultures on other standardized measures of language in school-age children. One possibility is that variability compresses on most standard vocabulary and grammar measures simply because functional communication is possible for nearly all speakers, but variation transfers instead to more "leading edge" domains like literacy or discourse comprehension. 

More generally, we are curious about how the range of variation we observed here relates to the variation in other non-trivial aspects of cognition. If we were to obtain stable measures of mathematical cognition, for example, would we observe the same degree of variation? This extension points to one of the under-appreciated virtues of scale of the type we have explored here: by virtue of the quantitative measurement that it affords, scale can lead to brand new questions. 

## Learning processes

In Chapter \@ref(intro-theory), we introduced the idea of "process universals." These cannot be universals of content as all of the content being reported by parents filling CDI forms is language-specific. Instead, the idea of process universals is that there are processes that operate in different language context to produce the observed pattern of phenomena. These processes could be -- but need not be -- learner-internal. They could also operate at the level of the child-caregiver dyad, for example. What more can we say about them from the perspective of the discussion above?

As we have stressed throughout, the connections between the broad trends and tendencies that we observed and any specific learner- or dyad-level process are weak, at best. Many different processes can likely lead to the same outcome, thus the linkages we make here are abductive rather than deductive. Further, as with many abductive arguments, some amount of evidential weight is given to the prior probability of the theoretical proposal. Bearing all that in mind, we highlight three process-level connections that appear consistent with our data. 

### Language grows through interactional input

Without input, there can be no uptake. The importance of language input is a fundamental tenet of all models of word learning, from the simplest accumulator model [@mcmurray2007] through to more complex probabilistic and neural network models [e.g., @mcmurray2012;@frank2009;@fazly2010]. In all of these models, what is learned by the model is a function of the frequency and statistical distinctiveness of the learner's input. This conclusion is amply supported by a body of correlational research linking observed speech from children's caregivers to their vocabulary size [e.g., @hart1995;@hoff2003;@huttenlocher1991;@hurtado2008]. 

But quantity is not enough. Beyond the first order correlation of input quantity to language outcomes, a body of research now provides nuanced qualification. In a number of studies across cultures, child-directed speech is a better predictor than overall speech, even in cultures where this kind of speech is relatively rare [@weisleder2013;@shneidman2012]. One hypothesis is that child-directed speech provides more grounded moments in which word meanings can be inferred from context [@cartmill2013]. Indeed, in one study, a variety of measures of input quality -- including joint engagement as well as the presence of rituals and routines -- were better predictors of vocabulary size than pure quantity [@hirsh-pasek2015]. Of course, high-quality input must be developmentally appropriate, and for older children, language that is more syntactically complex supports complex syntax aqcuisition [@huttenlocher2002]. Presumably the evidence for the importance of grounded, engaged communication is at least in part due to its specific importance for younger learners who are engaged in discovering word meanings; other aspects of language gain importance for other learners [@hoff2006;@hoff2002b;@rowe2012].

We see many of our conclusions as fitting well into this broader picture. While we do not have predictors of individual children's input, the research presented in Chapter \@ref(items-prediction) suggests that even aggregated, average measures of input are relatively powerful predictors of word-by-word uptake. Of course, word frequency is a useful predictor of age of acquisition, especially for nouns. Even if high-quality, grounded instances are the appropriate learning input, greater frequency overall will -- all else being equal -- lead to greater frequency in the appropriate learning context. We further observed effects of solo frequency (being used in a one-word sentence) and mean length of utterance. These both are consistent with the idea that it is easier to learn meanings for words in shorter sentences, which pose both fewer word segmentation challenges and fewer word-meaning mapping ambiguities. In addition, the relative cross-linguistic consistency in these predictors suggests that the input-uptake connections that have largely been documented for English learners are likely to be robust for learners of other languages as well. 

The demographic differences in vocabulary we observed are also consistent with interactional-input theories of vocabulary development, in which the more higher-quality the input the child receives, the faster vocabulary grows. Under this hypothesis, children who are first-born and who have mothers with more education are likely to receive more and more higher-quality input. First-born children receive more input through their greater allocation of parent attention (though as we note in Chapter \@ref(demographics), first-born children's parents may also be more aware of their vocabulary). Children with mothers who have more education receive more and more higher-quality talk through the availability of more parent time, different values around talk, greater awareness of the role of interaction for young children, and perhaps differing parental practices [@evans2004;@farkas2004;@rowe2012b]. Our data do not differentially support this interpretation over other possibilities, but prior work leads us to favor this interpretation. In contrast, it is an open question the extent to which the sex differences we observed emerge due to interactional/input differences vs. other learner-internal factors. 

In addition, our analyses of demographic differences in the composition of children's early vocabulary are consistent with this view as well. Siblings have a high probability of knowing "brother" and "sister"; children from mothers with less education are more likely to know words for candy and sweets. Across cultures, the words that emerge from these analyses plausibly appear related to the ways that children's input differs across different learning contexts. In sum, across a number of our analyses, we see what are plausibly the residues of input through interaction, accreted across a range of different input conditions.


### Individual word meanings must be inferred based on (cross-situational) evidence

Cross-situational learning is the proposal that children use the statistical properties of how words are used across contexts to help them infer meaning [@gleitman1990;@siskind1996]. This specific proposal has been instantiated in a variety of associative learning experiments with both adults [@yu2007b;@yurovsky2015] and children [@smith2008;@vlach2013]. The specific mechanisms underlying learners' performance in these tasks are still controversial [e.g., @medina2011;@trueswell2013;@yurovsky2013;@yurovsky2015]. Despite this controversy, the general model of learning as proposed in these studies has rapidly become the default instantiation of how interactional input translates into learning [e.g., the models of @frank2009;@fazly2010;@mcmurray2012]. The basic idea is that children bring multiple information sources -- including statistical, social, and grammatical information -- to bear on resolving the referent of each utterance. Then, this information is accumulated and brought to bear on resolving reference in subsequent utterances. 

Several findings from our investigations are consistent with these general ideas. As noted above, the predictors of word difficulty we found in Chapter \@ref(items-prediction) are consistent with the general input-uptake viewpoint. In fact, it is very easy to see some of them playing out in the context of the general cross-situational learning proposal. Of course, frequency effects are ubiquitous in cross-situational learning models [though their specifics vary somewhat from model to model; e.g., @kachergis2012]. Further, on the cross-situational perspective, shorter sentences and especially single-word utterances are less confounded in terms of the information they provide about the relationship between words and their meanings. 

In Chapter \@ref(categories-syntactic), we observed a complicated cross-linguistic pattern of biases. Nouns were typically over-represented in early vocabulary to some exent, while predicate representation was quite variable. While this pattern likely emerges out of the contributions of a variety of different cognitive and cultural features, its broad outlines are in fact consistent with the cross-situational viewpoint. On this view, nouns are easy to learn because the more they are heard, the more opportunities children get to build consistent mappings between the words and their contextual referents. This regularity should be especially true for concrete nouns that are more likely to be found in grounded contexts [@gentner2001]. 

In contrast, verbs and other predicates cannot be acquired as easily from basic co-occurrence. Syntactically "light" verbs like "make" or "do" require some nominal information to constrain their meaning in context. And "heavier" verbs may still be systematically ambiguous without syntactic information [e.g., "chase"/"flee"; @gleitman1990]. Thus, verb learning -- and likely the learning of other predicates and many function words as well -- relies on a base of nouns and a basic comprehension of the syntactic structures in which they appear in order to infer meaning in context. This informational sequencing viewpoint predicts that these categories should be acquired relatively later, with relatively more support from shorter, easier-to-parse utterances (MLU as a predictor for predicates, for example). This account would explain cross-linguistic exceptions like Mandarin as cases where many early-learned verbs are semantically-transparent enough to be learned cross-situationally without syntactic information [following @tardif1996]. 

### Generalizations appear gradually 

As they are instantiated in the CDI, syntactic and morphological structures are fundamentally "item-based" in the sense of @tomasello2003. Since all syntactic information is instantiated in particular example items, every bit of knowledge that the CDI assesses is grounded in lexical items used in a specific construction. Although there may well be broader, more abstract generalizations that underly the growth of word order, we simply do not have the signal to address the presence or absence of such abstractions. 

That said, at the level of the measurements we have, our evidence is broadly consistent with the view of language as growing through the gradual induction of syntactic regularities through a reciprocal interaction with the acquisition of individual content words. Versions of this viewpoints exist throughout the broad theoretical space of language acquisition [e.g., @yang2016;@tomasello2003;@meylan2017], but all proposals rely on a learning mechanism in which generalizations about structure are graded and rely on the amount of evidence available. All such mechanisms would presumably predict some relationship individuals' grammatical and lexical abilities; an important target for future theoretical work in this area is to explore how tight these correlations are predicted to beon different viewpoints. 

Further complicating matters, the relationship between grammar and the lexicon is likely reciprocal. As content vocabulary grows, it provides both the groundwork for generalization of constructions [@tomasello2003;@goldberg2006] and also the specific content words necessary for the induction of predicate meanings (as described above in the case of verbs). In the other direction, as grammar grows, it also allows for better disambiguation of predicate meanings [@gleitman1990] and creates myriad other opportunities for learning. Both of these directions of longitudinal influence are present in at least one study [@brinchmann2018], although that study found that considerable shared variance between individuals was also due to the stability of both grammatical and lexical knowledge within individuals. 

As we disussed in Chapter \@ref(intro-theory), we do not see our work here as resolving long-standing debates about the nature of abstract syntactic representations. Instead, we hope our contribution is somewhat different -- we refocus the debate away from phenomena that make only occasional contact with the gross regularities of children's early language use in context. Instead, we focus on the pattern of observable changes in complexity and diversity of early language. We hope that this focus leads to theorizing that takes these observables as its primary predictive target.

## Conclusions

Developmental psychology often appears to be divided between two groups that do not communicate with one another. On the one hand, there are researchers interested in the ontogenetic and phylogenetic origins of knowledge -- the epistemological project of understanding how we reason about objects, communicate using language, or learn from other people [@carey2009;@spelke2007;@tomasello2010]. On the other hand, there are researchers interested in growth, change, and variation across individuals in psychometric constructs like executive function, working memory, and personality [@diamond2013;@gathercole1994;@ainsworth2015]. The first type of research has led to a productive union of philosophical and psychological ideas, addressing exciting questions in the history of philosophy using empirical methods [e.g., @gopnik2004;@carey2009]. In contrast, the second type has had its impact in connections to clinical practice and educational policy [e.g., @nelson2007;@diamond2011]. 

"Origins" research and "variations" research have often appeared to be traditions at odds with one another. While there are, of course, exceptions to this split, in many cases researchers in these two traditions read different journals, record different measures, use different research designs and statistical models, and often appear to be pursuing different goals.

Yet, language learning is an area where these traditions come together. The knowledge being acquired -- the stock of words in the child's lexicon -- is both the epistemic construct whose origins we are studying *and* the psychometric construct whose reliability across individuals we wish to assess. By studying the variability and consistency in the early lexicon, we can both study the origins of knowledge and the processes and factors by which human beings differ from one another across different cultural contexts, family environments, and genetic endowments.

In our work here, we sought generalizations in the universals and variations that hold across cultures and languages -- and took steps to tie these generalizations to processes of language learning. These generalizations are based in the "variations" approach via the Batesian project of using variability to constrain theory. Yet they are also about the "origins" of a very specific type of knowledge: knowledge of language. The ultimate aim of theorizing in this area must be broader than either "origins" or "variations" alone.

We hope that our work in compiling measurements of consistency and variability across languages is a beginning rather than an ending. At the end of this mansucript, we hope to have inspired potential for more new work than we did at the beginning. Although the number of children represented in our analyses is large, the number of languages, and their diversity across families, is quite small. And our models of acquisition -- especially those linking input to uptake -- are only a rough sketch of what is possible. In the end, however, our hope is that by showing what is possible in the quantitative study of language development, we illustrate a broader set of possibilities for a data-driven science of developmental change. 
