Variability in Learning Individual Words. Here we focus on splitting apart the vocabulary data into effects on individual words. What makes the word “dog” be learned earlier on average than the word “jump”?

Demographic effects. In this part, we focus on demographic differences in the learning of individual words. Braginsky et al. (2016b) reported on gender differences in the particular words in early vocabulary; we generalize this analysis to birth order and socio-economic status

Predicting early learning. Braginsky et al. (2016a) provides an analysis in which independent data sources (including transcripts of child-directed speech) are brought to bear as predictors of acquisition differences between words. This “age of acquisition prediction” model allows us to quantify the consistency and variability in predictor values across languages for particular words, using the UL approach to cross-linguistic analysis. 

# Variability in Learning Individual Words

By-item stuff like overall item trajectories, `gender-input`, and `uni_lemma` based cross-linguistic consistency things.
