# Conclusions {#theory}

In the preceding chapters, we have have presented evidence from a wide range of analyses of the Wordbank dataset. These analyses have revealed both striking variability across our units of sampling -- children, primarily, but also words and even languages -- but they have also revealed substantial consistency. In this conclusion we discuss the interplay and tension between these two ideas, variability and consistency, and how they interact with and inform theoretical conceptions of language acquisition more broadly.

## Summary Observations

### Variability

Beginning with the first monograph reporting the CDI norming study, @fenson1994 noted that variability is perhaps the primary and most striking fact about children's vocabulary learning. In Chapter \@ref(vocab), we quantified this variability and found that -- across languages and spanning children's second year -- the variability was as large as the central tendency. 

In practical terms, the huge variance across children accounts for the fact that while some typically-developing two year olds will talk your ear off, others will barely utter a handful of words (even if they understand more). From a biological perspective, this variability is quite unprecedented. As a comparison, variation in heights for toddlers is tiny compared with variation in vocabulary: the mean height for a 24-month-old is around 33 inches, with a standard deviation of a little more than an inch, leading to a coefficient of variation around .03. This measurement is almost two orders of magnitude smaller than the coefficient of variation on vocabulary. 


### Consistency 

How can we describe and explain this variability? While much of the variance in the distribution of children remains unexplained, we still observe some striking correlates that can provide 
 In this sense, our work here follows what we might call the "Batesian program," the use of large-N data from the CDI to identify consistent developmental patterns that give clues to the organization of the mechanisms of language acquisition. To provide grounding to our discussion, we review consistencies below:

**Demographic differences**. In Chapter \@ref(vocab), we explored demographic differences in vocabulary. With very limited exceptions, we see a consistent advantage for girls over boys in early word learning across languages. Similarly, across (a smaller set of) languages, children with earlier birth orders are reported to have larger vocabularies. Both of these demographic differences should be considered in light of the probability of reporting biases -- for example, parents might *expect* girls to have larger vocabularies and hence report more words on average [though perhaps the consistency of the female advantage is surprising given variation in gender biases and stereotypes across countries, e.g., @nosek2009]. We return to the issue of difficulties in causal inference below. 

**Category biases**. In Chapter \@ref(categories), 


## Process Universals

### Definition

Alternative hypotheses:
1. content universals: 
2. process universals
3. unique and idiosyncratic developmental trajectories


### Relation to other thoretical constructs



* The nativist empiricist debate
* domain-specific conent



### Limitations





NOT ENIVRONEMNTAL VS. GENTIC
CAN HAVE GENETIC AND ENVIRONMENTAL INFLUENCES ON PROCESSES



causal loops

* what about genetics

example: gender
