```{r gram_params}
params <- list(min_admins = 100, min_age_var = 8)
```

```{r gram_grammar_items}
morphosyntax_fields <- c("combine", "complexity", "word_forms", "word_endings",
                         "word_forms_nouns", "word_forms_verbs", 
                         "word_endings_nouns", "word_endings_verbs", 
                         "small_parts_of_words", "word_complexity",
                         "verb_endings", "sentence_structure")

get_coded_type <- function(type, definition) {
  if (type == "combine") return("combine")
  if (str_detect(type, "forms")) return("word_forms")
  if (str_detect(type, "endings")) return("word_endings")
  if (type == "complexity" | type == "sentence_structure") return("complexity")
  return(NA)
  # parts <- definition %>% str_split(" / ") %>% unlist()
  # if (length(parts) != 2) return(NA)
  # lengths <- parts %>% str_split("[ ']") %>% map_int(length)
  # if (lengths[1] == lengths[2]) return("complexity_morphology")
  # else return("complexity_syntax")
}

grammar_items <- items %>%
  filter(type %in% morphosyntax_fields) %>%
  mutate(coded_type = map2_chr(type, definition, get_coded_type)) %>%
  filter(!is.na(coded_type))
```

```{r gram_grammar_data}
num_words <- items %>%
  filter(type == "word") %>%
  count(language, form)

get_grammar_data <- function(inst_items) {
  
  inst_language <- unique(inst_items$language)
  inst_form <- unique(inst_items$form)
  print(paste(inst_language, inst_form))
  
  inst_admins <- admins %>%
    filter(language == inst_language, form == inst_form) %>%
    select(language, form, source_name, age, data_id, production) %>%
    left_join(num_words) %>%
    mutate(production_prop = production / n)

  inst_grammar_data <- get_instrument_data(language = inst_language,
                                           form = inst_form, 
                                           items = inst_items$item_id,
                                           iteminfo = inst_items,
                                           administrations = inst_admins)

  inst_grammar_data %>%
    group_by(source_name, type) %>%
    filter(!all(is.na(value))) %>%
    group_by(data_id, type) %>%
    filter(!all(is.na(value))) %>%
    select(language, form, source_name, age, data_id, production,
           production_prop, item_id, definition, type, coded_type, value)
  
}

grammar_data <- grammar_items %>%
  split(paste(.$language, .$form)) %>%
  map_df(get_grammar_data)

write_feather(grammar_data, "data/grammar/grammar_data.feather")
```

```{r gram_grammar_data_coded}
# grammar_data <- read_feather("data/grammar/grammar_data.feather")

num_age_admins <- grammar_data %>%
  ungroup() %>%
  distinct(language, form, age, data_id) %>%
  group_by(language, form) %>%
  summarise(age_var = var(age),
            num_admins = n())

exclude <- num_age_admins %>%
  filter(num_admins < params$min_admins | age_var < params$min_age_var)

grammar_data_filtered <- grammar_data %>%
  left_join(num_age_admins) %>%
  filter(num_admins > params$min_admins, age_var > params$min_age_var)

positive_values <- c("produces", "yes", "complex", "sometimes", "often")

grammar_data_coded <- grammar_data_filtered %>%
  group_by(language, form, type, item_id) %>%
  mutate(raw_value = value,
         numeric_value = suppressWarnings(as.numeric(value)),
         numeric_scale = all((is.na(value) | nchar(value) == 0) ==
                               (is.na(numeric_value))),
         numeric_value = if_else(numeric_scale & nchar(value) == 0, 0,
                                 numeric_value),
         numeric_cutoff = mean(unique(numeric_value), na.rm = TRUE),
         value = case_when(
           is.na(value) ~ NA,
           type == "combine" & language == "French (Quebec)" & age >= 24 ~
             value %in% c("not yet", "sometimes"),
           numeric_scale ~ numeric_value >= numeric_cutoff,
           TRUE ~ value %in% positive_values
         )) %>%
  group_by(language, form, coded_type, type) %>%
  mutate(value = if_else(sum(!is.na(unique(value))) < 2 & is.na(value),
                         FALSE, value))

write_feather(grammar_data_coded, "data/grammar/grammar_data_coded.feather")
```

```{r gram_grammar_summary}
grammar_summary <- grammar_data_coded %>%
  filter(!is.na(value)) %>%
  group_by(language, form, age, data_id, coded_type,
           production, production_prop) %>%
  summarise(num_items = n(),
            positive = sum(value),
            negative = num_items - positive,
            prop = positive / num_items) %>%
  mutate(instrument = paste(language, form))

write_feather(grammar_summary, "data/grammar/grammar_summary.feather")
```
