--- 
title: "Investigating Early Language Learning Using Cross-Linguistic Parent-Report Data"
author: "Mika Braginsky, Daniel Yurovsky, Virginia Marchman, Michael Frank"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: langcog/wordbank-book
description: ""
output:
  bookdown::gitbook
---

# Introduction

How does children's language grow and change over their first years? 

Parent report is one powerful method for investigating. The developers of the MacArthur-Bates Communicative Development Inventory forms (CDIs) created a set of instruments for providing a broad overview of children's language.^[For purposes of clarity and ease throughout we refer to CDIs (the family of instruments) rather than the MB-CDI (the particular English forms).]

This book is a dynamic document that summarises descriptive patterns and theoretical conclusions from the examination of a large database of CDI data through the Wordbank project [@frank2016].

## Theories of Language Acquisition

There are many approaches to studying language learning. We distinguish a couple of major touchstones theories so that we can refer back to them.

Theories of vocabulary acquisition:

+ Constraints and Biases [@markman1990]
+ Cross-situational Learning [@yu2007]


Theories of grammatical acquisition:

+ Constructivist
+ Principles and Parameters

## The MacArthur-Bates Communicative Development Inventory

The original norming study. [@fenson1994]

### Measurement Properties

Decent reliability and validity for English. 

Need to review other evidence on this. 

### Cross-linguistic Approach

Adaptation, not translation!

## The Wordbank Project

Overview of our efforts to archive existing datasets 

## Organization of our Analyses

Our analyses are organized by different ways of cutting our data:

+ Vocabulary: total numbers of words said or understood by individuals, examined via demographic and longitudinal methods.
+ Word categories: What word categories are learned earlier or later? How do these patterns vary across languages?
+ Individual words: What words are learned earlier or later? Are there demographic or category differences in words? 
+ Grammatical items: How does grammatical complexity change across development? How is it related to the growth of the lexicon?
+ Gesture items: How does gesture relate to early language?

But, we also discuss cross-cutting theoretical themes for each analysis. 

## Theoretical Themes of our Analyses

+ Variation: Children vary tremendously. What predicts that variation? 
+ Consistency: Are there theoretical 
